operator:
  rollOutPods: true
  dashboards:
    enabled: true
    namespace: monitoring
  prometheus:
    serviceMonitor:
      enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
resources:
  limits:
    cpu: 1000m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 384Mi
rollOutCiliumPods: true
encryption:
  enabled: true
  type: wireguard
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"
k8sServiceHost: "127.0.0.1"
socketLB:
  hostNamespaceOnly: true
k8s:
  requireIPv4PodCIDR: true
ipam:
  mode: kubernetes
MTU: 1450
endpointRoutes:
  enabled: true
loadBalancer:
  acceleration: best-effort
bpf:
  masquerade: true
envoy:
  enabled: false
hubble:
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
  ui:
    enabled: true
    rollOutPods: true
    backend:
      resources:
        limits:
          cpu: 1000m
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 64Mi
    frontend:
      resources:
        limits:
          cpu: 1000m
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 64Mi
  metrics:
    enabled:
      # - "dns:query;ignoreAAAA"
      # - drop
      # - tcp
      # - flow
      # - icmp
      # - http
      - policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace
    dashboards:
      enabled: true
      namespace: monitoring
    serviceMonitor:
      enabled: true
routingMode: native
installNoConntrackIptablesRules: true
cni:
  customConf: true
dashboards:
  enabled: true
  namespace: monitoring
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
