configuration:
  period: 1m
  forceReboot: true
  drainTimeout: 1m

tolerations:
  - operator: "Exists"
    effect: "NoExecute"

metrics:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 32Mi
