auth:
  existingSecretPasswordKey: redis-password
  usePasswordFiles: false

replica:
  persistence:
    enabled: false
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 2000m
      memory: 64Mi
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
  nodeSelector:
    node.kubernetes.io/role: storage

sentinel:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 2000m
      memory: 32Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  requests:
    cpu: 100m
    memory: 32Mi
  limits:
    cpu: 2000m
    memory: 32Mi
