container_runtime: containerd

lapi:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  persistentVolume:
    data:
      enabled: false
    config:
      enabled: false
  storeCAPICredentialsInSecret: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik

  env:
    - name: COLLECTIONS
      value: crowdsecurity/traefik

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

appsec:
  enabled: true
  acquisitions:
    - source: appsec
      listen_addr: "0.0.0.0:7422"
      path: /
      appsec_config: crowdsecurity/appsec-default
      labels:
        type: appsec
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
