container_runtime: containerd

config:
  config.yaml.local: |
    api:
      server:
        auto_registration:
          enabled: true
          token: "${REGISTRATION_TOKEN}"
          allowed_ranges:
            - "127.0.0.1/32"
            - "192.168.0.0/16"
            - "10.0.0.0/8"
            - "172.16.0.0/12"

lapi:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  persistentVolume:
    data:
      enabled: false
    config:
      enabled: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik

  env:
    - name: COLLECTIONS
      value: crowdsecurity/traefik

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

appsec:
  enabled: true
  acquisitions:
    - source: appsec
      listen_addr: "0.0.0.0:7422"
      path: /
      appsec_config: crowdsecurity/virtual-patching
      labels:
        type: appsec
  env:
    - name: COLLECTIONS
      value: crowdsecurity/appsec-virtual-patching
    - name: APPSEC_CONFIGS
      value: "crowdsecurity/appsec-default"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
