ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - private

deployment:
  replicas: 2

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule

priorityClassName: system-cluster-critical

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    asDefault: true
    # middlewares:
    #   - crowdsec-middleware-bouncer@kubernetescrd
  ssh:
    port: 2222
    exposedPort: 22
    expose:
      default: true
  private:
    port: 9443
    exposedPort: 443
    expose:
      default: false
      internal: true
    tls:
      enabled: true

logs:
  access:
    enabled: true
    format: "json"

metrics:
  prometheus:
    serviceMonitor:
      enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 256Mi

service:
  annotations:
    load-balancer.hetzner.cloud/name: ${load_balancer_name}-traefik
    load-balancer.hetzner.cloud/type: ${load_balancer_type}
    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    load-balancer.hetzner.cloud/algorithm-type: round_robin
    load-balancer.hetzner.cloud/health-check-interval: 15s
    load-balancer.hetzner.cloud/health-check-timeout: 10s
    load-balancer.hetzner.cloud/health-check-retries: "3"
  additionalServices:
    internal:
      type: ClusterIP
