serviceMonitor:
  enabled: true

deploymentStrategy:
  type: Recreate

persistence:
  enabled: false
  # size: 1Gi
  # storageClassName: longhorn

sidecar:
  alerts:
    enabled: true
  datasources:
    enabled: true
  dashboards:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 384Mi

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    top-line:
      gnetId: 15474
      revision: 4
      datasource: prometheus
    health:
      gnetId: 15486
      revision: 3
      datasource: prometheus
    kubernetes:
      gnetId: 15479
      revision: 2
      datasource: prometheus
    namespace:
      gnetId: 15478
      revision: 3
      datasource: prometheus
    deployment:
      gnetId: 15475
      revision: 6
      datasource: prometheus
    pod:
      gnetId: 15477
      revision: 3
      datasource: prometheus
    service:
      gnetId: 15480
      revision: 3
      datasource: prometheus
    route:
      gnetId: 15481
      revision: 3
      datasource: prometheus
    authority:
      gnetId: 15482
      revision: 3
      datasource: prometheus
    cronjob:
      gnetId: 15483
      revision: 3
      datasource: prometheus
    job:
      gnetId: 15487
      revision: 3
      datasource: prometheus
    daemonset:
      gnetId: 15484
      revision: 3
      datasource: prometheus
    replicaset:
      gnetId: 15491
      revision: 3
      datasource: prometheus
    statefulset:
      gnetId: 15493
      revision: 3
      datasource: prometheus
    replicationcontroller:
      gnetId: 15492
      revision: 4
      datasource: prometheus
    prometheus:
      gnetId: 15489
      revision: 2
      datasource: prometheus
    prometheus-benchmark:
      gnetId: 15490
      revision: 2
      datasource: prometheus
    # multicluster:
    #   gnetId: 15488
    #   revision: 3
    #   datasource: prometheus
    # certmanager:
    #   gnetId: 20842
    #   revision: 2
    # traefik:
    #   gnetId: 17347
    #   revision: 8
    # longhorn:
    #   gnetId: 16888
    #   revision: 9
    # redis:
    #   gnetId: 763
    #   revision: 6
    #   datasource:
    #     - name: DS_PROM
    #       value: prometheus
    # crowdsec:
    #   url: https://raw.githubusercontent.com/crowdsecurity/grafana-dashboards/master/dashboards_v5/Crowdsec%20Overview.json
    #   datasource: prometheus
