serviceMonitor:
  enabled: true

deploymentStrategy:
  type: Recreate

persistence:
  enabled: true
  size: 1Gi
  storageClassName: longhorn

sidecar:
  alerts:
    enabled: true
  datasources:
    enabled: true
  dashboards:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 384Mi
