read:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

backend:
  replicas: 1
  persistence:
    storageClass: longhorn
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi

write:
  replicas: 2
  persistence:
    storageClass: longhorn
    size: 2Gi
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
  nodeSelector:
    node.kubernetes.io/role: "storage"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

gateway:
  service:
    labels:
      prometheus.io/service-monitor: "false"

loki:
  auth_enabled: false
  compactor:
    retention_enabled: true
    delete_request_store: s3
  storage_config:
    object_prefix: loki
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

chunksCache:
  enabled: false

resultsCache:
  enabled: false

monitoring:
  dashboards:
    enabled: true
    namespace: monitoring
  serviceMonitor:
    enabled: true
