deploymentMode: SingleBinary

read:
  replicas: 0

backend:
  replicas: 0

write:
  replicas: 0

gateway:
  enabled: false

loki:
  auth_enabled: false
  compactor:
    retention_enabled: true
    delete_request_store: s3
  storage_config:
    object_prefix: loki
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

chunksCache:
  enabled: false

resultsCache:
  enabled: false

singleBinary:
  replicas: 1
  tolerations:
    - key: node-role.kubernetes.io/monitor
      operator: Exists
  nodeSelector:
    node.kubernetes.io/role: "monitor"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 512Mi

monitoring:
  dashboards:
    enabled: true
    namespace: monitoring
  serviceMonitor:
    enabled: true
