config:
  clients:
    - url: http://loki:3100/loki/api/v1/push

tolerations:
  - effect: NoExecute
    operator: Exists

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 96Mi

serviceMonitor:
  enabled: true
