prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 8GB
    serviceMonitorSelector:
      matchLabels: null
    podMonitorSelector:
      matchLabels: null
    enableRemoteWriteReceiver: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 8Gi
    tolerations:
      - key: node-role.kubernetes.io/monitor
        operator: Exists
    nodeSelector:
      node-role.kubernetes.io/monitor: "true"
    resources:
      requests:
        cpu: 1000m
        memory: 2.5Gi
      limits:
        cpu: 2000m
        memory: 2.5Gi

grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true

alertmanager:
  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
