tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 1000m
    memory: 96Mi

serviceMonitor:
  enabled: true
