tempo:
  storage:
    trace:
      backend: s3
      s3:
        prefix: tempo
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-operated.monitoring:9090/api/v1/write
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 256Mi

serviceMonitor:
  enabled: true

tolerations:
  - key: node-role.kubernetes.io/storage
    operator: Exists

nodeSelector:
  node.kubernetes.io/role: "storage"
